kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: kube-system
  name: kibana
rules:
- apiGroups: [""]
  resources: ["services/proxy"]
  verbs: ["create", "get", "post", "update", "delete"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kibana
  namespace: kube-system
subjects:
- kind: User
  name: system:anonymous
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: kibana
  apiGroup: rbac.authorization.k8s.io
